name: Create new (pre-)release

on:
    push:
        tags:
            - "rd6006-v[0-9]+.[0-9]+.[0-9]+" # Release
            - "rd6006-v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+" # Pre-release

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: "write"
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ssh-key: ${{ secrets.WINGTRA_ALL_REPOS_SSH_PRIVATE_KEY }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: "pip" # Cache pip dependencies
                  check-latest: true

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel build

            - name: Build wheels
              run: |
                  python -m build -o dist

            - name: Create Pre-Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "dist/*"  # Include .tar.gz and .whl files
                  prerelease: true
                  generateReleaseNotes: true
              if: ${{ contains(github.ref, '-rc') }}

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "dist/*"  # Include .tar.gz and .whl files
                  prerelease: false
                  generateReleaseNotes: true
              if: ${{ !contains(github.ref, '-rc') }}
